export interface Retreat {
  name: string;
  location: string;
  country: string;
  price: number;
  priceDisplay: string;
  nights: number;
  nightsDisplay: string;
  type: string;
  includes: string;
  goodFor: string[];
  tags: string[];
  verified: boolean;
  communityRun: boolean;
  workExchange: boolean;
  scholarship: boolean;
  slidingScale: boolean;
}

export const retreats: Retreat[] = [
  // Under $500
  { name: "The Nothing Retreat", location: "Vermont", country: "US", price: 280, priceDisplay: "$280", nights: 3, nightsDisplay: "3 nights", type: "Unstructured stay", includes: "Private room, 3 meals/day, nature trails", goodFor: ["Burnout", "Stopping"], tags: ["Secular", "Solo-friendly", "Unstructured"], verified: true, communityRun: false, workExchange: false, scholarship: false, slidingScale: false },
  { name: "Noble Silence Weekend", location: "Catskills, NY", country: "US", price: 320, priceDisplay: "$320", nights: 3, nightsDisplay: "3 nights", type: "Silent retreat", includes: "Shared room, meals, meditation hall", goodFor: ["Quiet", "Burnout"], tags: ["Silent", "Secular", "Meditation optional"], verified: true, communityRun: false, workExchange: false, scholarship: false, slidingScale: true },
  { name: "Gaia House", location: "Devon, England", country: "UK", price: 340, priceDisplay: "$340", nights: 5, nightsDisplay: "5 nights", type: "Meditation retreat", includes: "Shared room, vegetarian meals, teacher-led sits", goodFor: ["Anxiety", "Burnout", "Quiet"], tags: ["Secular", "Donation-based", "Silent"], verified: true, communityRun: true, workExchange: false, scholarship: false, slidingScale: true },
  { name: "Still Here Grief Retreat", location: "Vermont", country: "US", price: 350, priceDisplay: "$350", nights: 3, nightsDisplay: "3 nights", type: "Grief retreat", includes: "Shared room, meals, facilitated circles", goodFor: ["Grief", "Loneliness"], tags: ["Trauma-informed", "Solo-friendly", "Sliding scale"], verified: true, communityRun: false, workExchange: false, scholarship: false, slidingScale: true },
  { name: "Caregiver Respite Weekend", location: "Blue Ridge, VA", country: "US", price: 350, priceDisplay: "$350", nights: 3, nightsDisplay: "3 nights", type: "Respite retreat", includes: "Private room, meals, peer support", goodFor: ["Caregivers", "Burnout"], tags: ["Secular", "Women-focused", "Sliding scale"], verified: true, communityRun: false, workExchange: false, scholarship: true, slidingScale: true },
  { name: "Rest & Restore Weekend", location: "Catskills, NY", country: "US", price: 380, priceDisplay: "$380", nights: 3, nightsDisplay: "3 nights", type: "Rest retreat", includes: "Private room, meals, nature", goodFor: ["Burnout", "Stopping"], tags: ["Secular", "Solo-friendly", "Meals included"], verified: true, communityRun: false, workExchange: false, scholarship: false, slidingScale: false },
  { name: "Belonging Weekend", location: "Hudson Valley, NY", country: "US", price: 380, priceDisplay: "$380", nights: 3, nightsDisplay: "3 nights", type: "Community retreat", includes: "Shared room, meals together, optional activities", goodFor: ["Loneliness", "Depression"], tags: ["Community", "Meals together", "Nature"], verified: true, communityRun: false, workExchange: false, scholarship: false, slidingScale: false },
  { name: "Simple Stop", location: "Portugal", country: "PT", price: 380, priceDisplay: "$380", nights: 4, nightsDisplay: "4 nights", type: "Unstructured stay", includes: "Shared room, meals, coastal access", goodFor: ["Stopping", "Burnout"], tags: ["Coastal", "Donation-based", "No program"], verified: true, communityRun: true, workExchange: false, scholarship: false, slidingScale: true },
  { name: "Holy Cross Monastery", location: "West Park, NY", country: "US", price: 385, priceDisplay: "$385", nights: 5, nightsDisplay: "5 nights", type: "Monastery stay", includes: "Private room, 3 meals/day, chapel access", goodFor: ["Quiet", "Grief", "Stopping"], tags: ["Religious-optional", "Silent", "Solo-friendly"], verified: true, communityRun: true, workExchange: false, scholarship: false, slidingScale: true },
  { name: "Gentle Days Retreat", location: "Asheville, NC", country: "US", price: 400, priceDisplay: "$400", nights: 4, nightsDisplay: "4 nights", type: "Depression recovery", includes: "Private room, meals, nature therapy", goodFor: ["Depression", "Burnout"], tags: ["Trauma-informed", "Sliding scale", "Nature"], verified: true, communityRun: false, workExchange: false, scholarship: true, slidingScale: true },
  { name: "The Quiet Farm", location: "Devon, UK", country: "UK", price: 400, priceDisplay: "$400", nights: 5, nightsDisplay: "5 nights", type: "Farm stay", includes: "Private room, meals, farm access", goodFor: ["Quiet", "Stopping"], tags: ["Nature", "Solo-friendly", "Meals included"], verified: true, communityRun: true, workExchange: true, scholarship: false, slidingScale: false },
  { name: "Cabin & Quiet", location: "Montana", country: "US", price: 420, priceDisplay: "$420", nights: 5, nightsDisplay: "5 nights", type: "Cabin retreat", includes: "Private cabin, meals delivered, off-grid", goodFor: ["Stopping", "Burnout", "Quiet"], tags: ["Private cabin", "Meals delivered", "Off-grid"], verified: true, communityRun: false, workExchange: false, scholarship: false, slidingScale: false },
  { name: "Grief & Gratitude Weekend", location: "Sonoma, CA", country: "US", price: 420, priceDisplay: "$420", nights: 3, nightsDisplay: "3 nights", type: "Grief retreat", includes: "Shared room, meals, facilitated circles", goodFor: ["Grief", "Loneliness"], tags: ["Secular", "Small group", "Nature"], verified: true, communityRun: false, workExchange: false, scholarship: false, slidingScale: false },
  { name: "Mountain Silence Retreat Center", location: "Blue Ridge Mountains, NC", country: "US", price: 450, priceDisplay: "$450", nights: 4, nightsDisplay: "4 nights", type: "Silent retreat", includes: "Private room, 3 meals/day, guided meditation", goodFor: ["Burnout", "Overwhelm"], tags: ["Secular", "Silent", "Solo-friendly"], verified: true, communityRun: false, workExchange: false, scholarship: false, slidingScale: false },
  { name: "Parallel Presence", location: "Maine", country: "US", price: 450, priceDisplay: "$450", nights: 4, nightsDisplay: "4 nights", type: "Connection retreat", includes: "Shared room, meals, coastal walks", goodFor: ["Loneliness", "Depression"], tags: ["Coastal", "Art optional", "Solo-friendly"], verified: true, communityRun: false, workExchange: false, scholarship: false, slidingScale: false },
  { name: "The Brave Space", location: "Scotland", country: "UK", price: 450, priceDisplay: "$450", nights: 4, nightsDisplay: "4 nights", type: "Trauma-sensitive retreat", includes: "Private room, meals, facilitated sessions", goodFor: ["Trauma", "Depression"], tags: ["Women-only", "Trauma-informed", "Sliding scale"], verified: true, communityRun: false, workExchange: false, scholarship: true, slidingScale: true },
  { name: "The Soft Landing", location: "Cornwall, UK", country: "UK", price: 480, priceDisplay: "$480", nights: 5, nightsDisplay: "5 nights", type: "Depression recovery", includes: "Private room, meals, art therapy", goodFor: ["Depression", "Grief"], tags: ["Secular", "Art therapy", "Meals included"], verified: true, communityRun: false, workExchange: false, scholarship: false, slidingScale: false },
  // Under $750
  { name: "Trauma-Sensitive Retreat", location: "Oregon", country: "US", price: 520, priceDisplay: "$520", nights: 4, nightsDisplay: "4 nights", type: "Trauma-sensitive", includes: "Private room, meals, somatic sessions", goodFor: ["Trauma", "Depression"], tags: ["Trauma-informed", "Small group", "Nature"], verified: true, communityRun: false, workExchange: false, scholarship: true, slidingScale: true },
  { name: "The Pause Retreat", location: "Lake District, UK", country: "UK", price: 520, priceDisplay: "$520", nights: 5, nightsDisplay: "5 nights", type: "Caregiver retreat", includes: "Private room, meals, peer support", goodFor: ["Caregivers", "Burnout"], tags: ["Nature", "Peer support", "Meals included"], verified: true, communityRun: false, workExchange: false, scholarship: false, slidingScale: false },
  { name: "Digital Detox Cabin Stay", location: "Olympic Peninsula, WA", country: "US", price: 550, priceDisplay: "$550", nights: 5, nightsDisplay: "5 nights", type: "Digital detox", includes: "Private cabin, meals, nature guides", goodFor: ["Burnout", "Overwhelm"], tags: ["Nature", "Silent-optional", "Private room"], verified: true, communityRun: false, workExchange: false, scholarship: false, slidingScale: false },
  { name: "Mountain Stillness", location: "Colorado", country: "US", price: 550, priceDisplay: "$550", nights: 5, nightsDisplay: "5 nights", type: "Silent retreat", includes: "Semi-private room, meals, meditation", goodFor: ["Quiet", "Burnout"], tags: ["Silent", "Private cabin", "Nature"], verified: true, communityRun: false, workExchange: false, scholarship: false, slidingScale: false },
  { name: "Walking Through Loss", location: "Lake District, UK", country: "UK", price: 580, priceDisplay: "$580", nights: 5, nightsDisplay: "5 nights", type: "Walking pilgrimage", includes: "Shared room, meals, guided walks", goodFor: ["Grief", "Loneliness"], tags: ["Walking pilgrimage", "Community", "Meals included"], verified: true, communityRun: false, workExchange: false, scholarship: false, slidingScale: false },
  { name: "The Table Retreat", location: "Provence, France", country: "FR", price: 620, priceDisplay: "$620", nights: 5, nightsDisplay: "5 nights", type: "Connection retreat", includes: "Shared room, cooking together, farm stay", goodFor: ["Loneliness", "Depression"], tags: ["Cooking together", "Small group", "Farm stay"], verified: true, communityRun: true, workExchange: true, scholarship: false, slidingScale: false },
  { name: "Spirit Rock Meditation Center", location: "Woodacre, CA", country: "US", price: 650, priceDisplay: "$650", nights: 5, nightsDisplay: "5 nights", type: "Insight meditation", includes: "Shared room, meals, daily teacher meetings", goodFor: ["Trauma", "Grief", "Quiet"], tags: ["Secular", "Trauma-informed", "Sliding scale"], verified: true, communityRun: true, workExchange: false, scholarship: true, slidingScale: true },
  { name: "Winter Light Retreat", location: "Sweden", country: "SE", price: 650, priceDisplay: "$650", nights: 6, nightsDisplay: "6 nights", type: "Nature retreat", includes: "Private cabin, meals, sauna, nature therapy", goodFor: ["Depression", "Burnout"], tags: ["Nature therapy", "Community", "Sauna"], verified: true, communityRun: false, workExchange: false, scholarship: false, slidingScale: false },
  { name: "Plum Village Practice Center", location: "Dordogne, France", country: "FR", price: 680, priceDisplay: "$680", nights: 7, nightsDisplay: "7 nights", type: "Mindfulness community", includes: "Shared room, all meals, daily practice", goodFor: ["Grief", "Loneliness"], tags: ["Buddhist-inspired", "Community", "Work practice"], verified: true, communityRun: true, workExchange: true, scholarship: true, slidingScale: true },
  { name: "Embodied Safety", location: "New Mexico", country: "US", price: 680, priceDisplay: "$680", nights: 5, nightsDisplay: "5 nights", type: "Somatic retreat", includes: "Private room, meals, somatic sessions", goodFor: ["Trauma", "Depression"], tags: ["Somatic", "Consent-based", "Private room"], verified: true, communityRun: false, workExchange: false, scholarship: false, slidingScale: false },
  { name: "Caregiver Breathe Again", location: "Costa Rica", country: "CR", price: 680, priceDisplay: "$680", nights: 7, nightsDisplay: "7 nights", type: "Caregiver retreat", includes: "Shared room, meals, optional yoga", goodFor: ["Caregivers", "Burnout"], tags: ["Tropical", "Yoga optional", "Community"], verified: true, communityRun: false, workExchange: false, scholarship: false, slidingScale: false },
  // Under $1000
  { name: "Slow Living Retreat", location: "Tuscany, Italy", country: "IT", price: 720, priceDisplay: "$720", nights: 7, nightsDisplay: "7 nights", type: "Slow living", includes: "Shared room, farm-to-table meals, art optional", goodFor: ["Burnout", "Creative block"], tags: ["Community", "Farm-to-table", "Art optional"], verified: true, communityRun: true, workExchange: true, scholarship: false, slidingScale: false },
  { name: "Kripalu Center for Yoga", location: "Stockbridge, MA", country: "US", price: 750, priceDisplay: "$750", nights: 5, nightsDisplay: "5 nights", type: "Wellness center", includes: "Shared room, 3 buffet meals/day, all classes", goodFor: ["Depression", "Burnout", "First-timers"], tags: ["Spiritual-optional", "Neurodivergent-aware", "LGBTQ+ welcoming"], verified: true, communityRun: false, workExchange: false, scholarship: true, slidingScale: true },
  { name: "Deep Forest Immersion", location: "British Columbia, Canada", country: "CA", price: 820, priceDisplay: "$820", nights: 7, nightsDisplay: "7 nights", type: "Nature immersion", includes: "Private cabin, meals, forest bathing guides", goodFor: ["Burnout", "Depression", "Stopping"], tags: ["Nature", "Solo-friendly", "Off-grid"], verified: true, communityRun: false, workExchange: false, scholarship: false, slidingScale: false },
  { name: "The Long Exhale", location: "Bali, Indonesia", country: "ID", price: 850, priceDisplay: "$850", nights: 10, nightsDisplay: "10 nights", type: "Extended rest", includes: "Private room, all meals, yoga optional", goodFor: ["Burnout", "Stopping", "Depression"], tags: ["Tropical", "Extended stay", "Solo-friendly"], verified: true, communityRun: false, workExchange: true, scholarship: false, slidingScale: false },
  { name: "Healing Waters Retreat", location: "Iceland", country: "IS", price: 950, priceDisplay: "$950", nights: 5, nightsDisplay: "5 nights", type: "Hot springs retreat", includes: "Shared room, meals, hot springs, guided hikes", goodFor: ["Burnout", "Grief", "Quiet"], tags: ["Nature", "Geothermal", "Small group"], verified: true, communityRun: false, workExchange: false, scholarship: false, slidingScale: false },
  // Free / Work exchange
  { name: "Esalen Work-Scholar Program", location: "Big Sur, CA", country: "US", price: 0, priceDisplay: "$0 (work exchange)", nights: 28, nightsDisplay: "28 nights", type: "Work exchange", includes: "Shared room, all meals, hot springs, 1 workshop/week", goodFor: ["Deep reset", "Career transition", "Burnout"], tags: ["Secular", "Community", "Physical work"], verified: true, communityRun: false, workExchange: true, scholarship: true, slidingScale: false },
  { name: "WWOOF Farm Stays", location: "Various worldwide", country: "Global", price: 0, priceDisplay: "$0 (work exchange)", nights: 14, nightsDisplay: "14+ nights", type: "Farm work exchange", includes: "Room, meals, farm life", goodFor: ["Stopping", "Loneliness", "Depression"], tags: ["Nature", "Physical work", "Community"], verified: true, communityRun: true, workExchange: true, scholarship: false, slidingScale: false },
  { name: "Insight Meditation Society", location: "Barre, MA", country: "US", price: 0, priceDisplay: "Donation-based", nights: 7, nightsDisplay: "7-9 nights", type: "Meditation retreat", includes: "Shared room, meals, teacher-led program", goodFor: ["Quiet", "Burnout", "Grief"], tags: ["Secular", "Donation-based", "Silent"], verified: true, communityRun: true, workExchange: false, scholarship: true, slidingScale: true },
];
